version: '3.8'

services:
  # Core Services
  acc:
    build: ./services/acc
    ports:
      - "8001:8000"
    environment:
      - ENV=development
    depends_on:
      - redis
      - kafka

  pdr:
    build: ./services/pdr
    ports:
      - "8002:8000"
    environment:
      - ENV=development
    depends_on:
      - redis
      - kafka

  arl:
    build: ./services/arl
    ports:
      - "8003:8000"
    environment:
      - ENV=development
    depends_on:
      - redis
      - kafka

  rca:
    build: ./services/rca
    ports:
      - "8004:8000"
    environment:
      - ENV=development
    depends_on:
      - redis
      - kafka

  crrak:
    build: ./services/crrak
    ports:
      - "8005:8000"
    environment:
      - ENV=development
    depends_on:
      - redis
      - kafka

  # Infrastructure Services
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  redis_data:
  grafana_data:
